In [8]:
import pandas as pd

## read csv

In [9]:
x = pd.read_csv('C:/Users/kaiqu/LAMIA/CARD 12/02 - Classificação Binária - Base Breast Cancer/entradas_breast.csv')
x

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [10]:
# classe
y = pd.read_csv('C:/Users/kaiqu/LAMIA/CARD 12/02 - Classificação Binária - Base Breast Cancer/saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

## sklearn

In [11]:
import sklearn
from sklearn.model_selection import train_test_split

In [12]:
# 75% pra treinar, 25% pra testar
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size = 0.25)

print(f'x_treinamento:\t {x_treinamento.shape}') # 426 registros para treinar, 30 previsores
print(f'y_treinamento:\t {y_treinamento.shape}')
print(f'x_teste:\t {x_teste.shape}') # 143 registro, 30 previsores
print(f'y_teste:\t {y_teste.shape}')

x_treinamento:	 (426, 30)
y_treinamento:	 (426, 1)
x_teste:	 (143, 30)
y_teste:	 (143, 1)


## tensorflow

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [14]:
tf.__version__

'2.17.0'

In [15]:
# (30 + 1) / 2
# = 15.5
# -> 16

In [32]:
rede_neural = Sequential([
    # shape = quantidade de neurônios na camada, 30 pois há 30 previsores
    # dense = rede neural densa. neuronio de uma camda est  conectado a todfos neuronios da proxima camda

    # camada de entrada
    tf.keras.layers.InputLayer(shape = (30,)),
    # camada oculta
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer='random_uniform'),
    # mais uma camada oculta
    tf.keras.layers.Dense(units = 16, activation='relu', kernel_initializer=('random_uniform')),
    # camada de saida
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])
# rede neural criada!

In [39]:
rede_neural.summary() # 496 = 30 * 16 + 16 (bias) -> neuronio adicional ligando-se a cada uma dos neuronios da camada de entrada
# 496 + 17 = 513
# 513 parametros totais, indicam os pesos que serão ajustados durante a etapa de treinamento

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [35]:
# learning é padrao 0.001
# o gradiente d cada peso é clipado para não ser maior que o valor passado como parêmtro
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [36]:
# optimizer = algoritmo de otimização
# loss = cálculo dos erros
# metrics = métrica de avaliação da rede neural (precisão)
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy'])

In [37]:
rede_neural.fit(x_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5911 - loss: 1.0059   
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - binary_accuracy: 0.7338 - loss: 0.5177
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - binary_accuracy: 0.8210 - loss: 0.4162
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - binary_accuracy: 0.7341 - loss: 0.5499
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - binary_accuracy: 0.7811 - loss: 0.5678
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - binary_accuracy: 0.8684 - loss: 0.3711
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - binary_accuracy: 0.8487 - loss: 0.4132
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - binary_accuracy: 0.8424 - loss: 0.3838
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - binary_accuracy: 0.8248 - loss: 0.4016
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - binary_accuracy: 0.8128 - loss: 0.5065
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - bi

In [41]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[-2.01208014e-02, -2.95982987e-01, -1.85327187e-01,
          1.33825436e-01, -3.54483068e-01,  1.58773690e-01,
          3.89179867e-03,  1.07393609e-02, -4.09144536e-02,
         -2.74246149e-02, -8.70137885e-02, -1.17549850e-02,
         -1.74473692e-02, -4.95664515e-02,  8.52029622e-02,
         -7.43374750e-02],
        [-4.26714160e-02, -2.79633313e-01, -1.99746251e-01,
          2.72859246e-01, -4.46832150e-01,  3.81905548e-02,
         -1.36956815e-02, -9.80838463e-02, -4.50005680e-02,
         -1.52827024e-01, -9.97298509e-02,  1.18030399e-01,
          1.93927437e-01,  7.00693727e-02,  3.71918716e-02,
         -1.76762685e-01],
        [ 5.44494763e-03, -7.95559809e-02,  7.91169405e-02,
          1.73499152e-01, -3.32455873e-01,  1.54669836e-01,
          8.42849538e-02,  6.54872879e-02,  1.49554526e-03,
         -1.03324212e-01, -9.09528136e-02,  6.63971528e-02,
         -8.64199642e-03, -7.97806755e-02, -6.87429085e-02,
          9.09301788e-02],
        [ 2.6965916

In [42]:
len(pesos0) # 2 arrays
# 1 array de cada neuronio da camada de entrada
# 1 array de cada neuronio da camada oculta

2

In [45]:
len(pesos0[1]) # 16 neuronios na camada oculta

16

In [47]:
# 30 valores, pesos de cada neuronio da camada de entrada com cada um dos neuronios da camada oculta
len(pesos0[0])

30

In [48]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[-9.59523674e-03, -5.91012910e-02,  1.20880874e-02,
         -1.07124351e-01, -4.28619273e-02,  2.85302699e-02,
         -7.13434443e-03, -5.71541786e-02,  3.05078626e-02,
          1.71147212e-01, -7.06161037e-02, -6.75285701e-03,
          4.41344362e-03, -1.15901744e-02, -3.52462046e-02,
         -6.42150491e-02],
        [-4.09961715e-02,  4.96783294e-02,  3.74717731e-03,
          1.23223616e-02,  1.46103259e-02, -4.76674549e-02,
          4.02067136e-03, -1.21896807e-02,  2.31119022e-01,
         -7.27374107e-02, -2.05888785e-02,  2.23033000e-02,
          2.04350688e-02, -4.18524966e-02,  2.56205313e-02,
         -6.59037754e-02],
        [-2.74444576e-02, -6.31281361e-02, -3.70098278e-02,
          7.07225502e-03, -1.10028861e-02, -4.69744485e-03,
         -5.89523278e-02,  1.04503267e-01,  1.11415818e-01,
         -2.57743653e-02,  1.58984810e-02,  1.95040144e-02,
         -3.67419049e-02, -1.11735247e-01, -9.99674108e-03,
         -2.62821862e-03],
        [-3.7487588

In [50]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2 # 16 neuronios na camada oculta ligados a camada saida + o do bias

[array([[-0.2564357 ],
        [ 0.06567337],
        [ 0.16781795],
        [ 0.19216558],
        [-0.47508198],
        [-0.14035487],
        [-0.00561823],
        [ 0.12687635],
        [ 0.17070256],
        [-0.17902124],
        [ 0.03072713],
        [-0.4718436 ],
        [-0.13237138],
        [-0.168199  ],
        [-0.07574373],
        [-0.65224427]], dtype=float32),
 array([0.4368106], dtype=float32)]

In [22]:
previsoes = rede_neural.predict(x_teste)
previsoes = (previsoes) > 0.5 # indica se a previsão é verdadeira ou falsa

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step


In [24]:
previsoes

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [

In [25]:
y_teste # comparando o true com o 1 para saber se é cancer ou não

0
208  1
117  0
214  0
442  1
138  0
..  ..
561  1
508  1
500  1
244  0
444  0

[143 rows x 1 columns]

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [27]:
accuracy_score(y_teste, previsoes)

0.8251748251748252

In [28]:
confusion_matrix(y_teste, previsoes)
# 53 + 65 = 118 acertos
# 21 +  4 = 25 erros
# 118 / 143 = 0.8251 (accuracy_score)
# erro = 25 / 143 = 0.1748

array([[53,  4],
       [21, 65]], dtype=int64)

In [38]:
rede_neural.evaluate(x_teste, y_teste)
# 0.53 erro
# 0.8251 acerto

# maior numero de camadas é só pra problemas mais complexos

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7201 - loss: 1.6732  


[1.6668457984924316, 0.6993007063865662]