In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout

In [3]:
x = pd.read_csv('entradas_breast.csv')
y = pd.read_csv('saidas_breast.csv')

In [4]:
classificador = Sequential()
classificador.add(InputLayer(shape=(30,)))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=1, activation='sigmoid'))

In [5]:
classificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [6]:
classificador.fit(x, y, batch_size=10, epochs=100)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - binary_accuracy: 0.4599 - loss: 1.9035
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - binary_accuracy: 0.6412 - loss: 0.6215
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - binary_accuracy: 0.6422 - loss: 0.5803
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - binary_accuracy: 0.7320 - loss: 0.5229
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - binary_accuracy: 0.6880 - loss: 0.5220
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - binary_accuracy: 0.7504 - loss: 0.4916
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - binary_accuracy: 0.7977 - loss: 0.4409
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8058 - loss: 0.4201
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - binary_accuracy: 0.7742 - loss: 0.4690
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - binary_accuracy: 0.7613 - loss: 0.4452
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - binar

In [7]:
x

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [8]:
novo = np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134,
                 0.178, 0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005,
                 0.04, 0.05, 0.015, 0.03, 0.007, 23.15, 16.64, 178.5,
                 2018, 0.14, 0.185, 0.84, 158, 0.363]])

In [9]:
novo

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-02, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

In [10]:
novo.size, novo.shape

(30, (1, 30))

In [11]:
previsao = classificador.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step


In [12]:
previsao

array([[1.]], dtype=float32)

In [13]:
previsao = previsao > 0.5
print(previsao)

[[ True]]


In [15]:
if previsao:
    print('maligno')
else:
    print('benigno')

maligno


In [16]:
classificador.save('classificador_breast.keras') # dá o arquivo que precisa pra carregar

In [17]:
classificador_novo = tf.keras.models.load_model('classificador_breast.keras')

In [18]:
classificador_novo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [19]:
classificador_novo.predict(novo) # simula o carregamento salvo previamente do classificador

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[1.]], dtype=float32)