In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [5]:
base = pd.read_csv('iris.csv')
base # 150 x 5

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
x = base.iloc[:, 0:4].values # : = todas as linhas # colunas 0 a 4 (3) menos o nome
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
y = base.iloc[:, 4].values # todas as linhas, só a coluna do nome
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [11]:
label_encoder = LabelEncoder() # transforma as strings em numeros
y = label_encoder.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [12]:
y = np_utils.to_categorical(y) # transforma os numeros em categorias
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [13]:
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size = 0.25)

In [14]:
x_treinamento.shape, x_teste.shape # 112 para treinar e 38 para testar

((112, 4), (38, 4))

In [15]:
y_treinamento.shape, y_teste.shape # 112 para treinar e 38 para testar

((112, 3), (38, 3))

## rede neural

In [16]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units = 4, activation='relu'),
    tf.keras.layers.Dense(units = 4, activation='relu'),
    tf.keras.layers.Dense(units = 3, activation='softmax'), # 3 por causa das 3 classes, softmax pela mesma causa
])
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
rede_neural.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [18]:
rede_neural.fit(x_treinamento, y_treinamento, batch_size=10, epochs = 1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.3334 - loss: 5.6458
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3973 - loss: 4.5535 
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3422 - loss: 4.5524 
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3715 - loss: 3.8777 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3501 - loss: 3.6141 
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - categorical_accuracy: 0.3098 - loss: 3.7736
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - categorical_accuracy: 0.3366 - loss: 3.3754
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - categorical_accuracy: 0.2982 - loss: 3.2181
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - categorical_accuracy: 0.3650 - loss: 2.6146
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - categorical_accuracy: 0.3103 - loss: 2.4861
Epoch

In [20]:
rede_neural.evaluate(x_teste, y_teste) # [0] valor da perda, [1] precisão

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9161 - loss: 0.1960 


[0.18946532905101776, 0.9210526347160339]

In [22]:
previsoes = rede_neural.predict(x_teste)
previsoes

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


array([[2.32272535e-13, 2.74003685e-01, 7.25996315e-01],
       [4.42150744e-18, 4.75921519e-02, 9.52407837e-01],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [9.06124234e-01, 9.35603827e-02, 3.15434620e-04],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [4.01000230e-19, 3.12179402e-02, 9.68782008e-01],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [1.83977376e-19, 2.71935035e-02, 9.72806513e-01],
       [3.30113499e-24, 3.81533848e-03, 9.96184647e-01],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [1.03646918e-20, 1.62821040e-02, 9.83717859e-01],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [1.01271970e-03, 9.74069417e-01, 2.49178149e-02],
       [8.85783806e-02, 9.02993381e-01, 8.42826534e-03],
       [9.73890960e-01, 2.60439236e-02, 6.50774891e-05],
       [3.23996587e-16, 9.91361

In [23]:
previsoes = previsoes > 0.5
print(previsoes)

[[False False  True]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]]


In [26]:
y_teste2 = [np.argmax(t) for t in y_teste]
print(y_teste2)


[2, 2, 0, 1, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 1, 1, 0, 2, 1, 1, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0]


In [29]:
previsoes2 = [np.argmax(t) for t in previsoes]
print(previsoes2)

[2, 2, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 1, 2, 0, 0, 2, 0, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 1, 1, 0]


In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(y_teste2, previsoes2)

0.9210526315789473

In [32]:
confusion_matrix(y_teste2, previsoes2)

array([[14,  0,  0],
       [ 2, 10,  1],
       [ 0,  0, 11]], dtype=int64)