In [1]:
import torch

In [3]:
x = torch.tensor([[1, 2, 3 ,4], [5, 6, 7, 8]])
print(x.shape)

torch.Size([2, 4])


In [4]:
# multiplicação
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [5]:
# soma
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [9]:
# reshape
print(x.shape)
x.view(1, 8)

torch.Size([2, 4])


tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [11]:
# squeeze
# tensor com 2 pilhas contendo uma linha e 10 colunas
a = torch.ones(2, 1, 10)
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [12]:
# tira o primeiro index do eixo que tinha penas um tamanho
print(f'shape pre squeeze: {a.shape}')
a_squeeze = a.squeeze()
print(f'shape pos squeeze: {a_squeeze.shape}')

shape pre squeeze: torch.Size([2, 1, 10])
shape pos squeeze: torch.Size([2, 10])


In [13]:
# como a posição 1 tem tamanho 2, não é possível fazer o squeeze
a = torch.ones(2, 2, 10)
print(f'shape pre squeeze: {a.shape}')
a_squeeze = a.squeeze(1)
print(f'shape pos squeeze: {a_squeeze.shape}')

shape pre squeeze: torch.Size([2, 2, 10])
shape pos squeeze: torch.Size([2, 2, 10])


In [14]:
# a posição 2 tem tamanho 1, por isso é possível
a = torch.ones(2, 3, 1)
print(f'shape pre squeeze: {a.shape}')
a_squeeze = a.squeeze(2)
print(f'shape pos squeeze: {a_squeeze.shape}')

shape pre squeeze: torch.Size([2, 3, 1])
shape pos squeeze: torch.Size([2, 3])


In [15]:
# unsqueeze
# oposto do squeeze, adiciona uma dimensão na posição especificada
a = torch.ones(2, 3)
print(f'shape pre unsqueeze: {a.shape}')
a_unsqueeze = a.unsqueeze(2)
print(f'shape pos unsqueeze: {a_unsqueeze.shape}')

shape pre unsqueeze: torch.Size([2, 3])
shape pos unsqueeze: torch.Size([2, 3, 1])


In [16]:
# indexando o [None]
a = torch.ones(2, 3)

print(a[None].shape)        # cria um axis falso no index 0
print(a[:, None].shape)     # cria um axis falso no index 1
print(a[:, :, None].shape)  # cria um axis falso no index

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


In [19]:
# multiplicação de matrizes
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]])
y = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [20]:
torch.matmul(x, y)

tensor([[ 70,  80,  90],
        [158, 184, 210]])

In [29]:
# concatenação
x = torch.randn(1, 4, 5)
z = torch.cat([x, x], axis = 1)
print('axis 1 concatenado:', x.shape, z.shape)  # 1, 8, 5

axis 1 concatenado: torch.Size([1, 4, 5]) torch.Size([1, 8, 5])


In [32]:
# permutação
x = torch.randn(3, 20, 10)
z = x.permute(2, 0, 1)
print('permutação:', x.shape, z.shape)  # 10, 3, 20

permutação: torch.Size([3, 20, 10]) torch.Size([10, 3, 20])
