In [2]:
import numpy as np # biblioteca para álgebra linear

In [3]:
minha_lista = [1,2,3]

In [4]:
np.array(minha_lista) # transforma a lista em array numpy

array([1, 2, 3])

In [5]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(minha_matriz) # transforma a matriz em array numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10) # cria uma array numpy de 0 a 9
np.arange(0, 10, 2) # 2 é o step, de quanto em quanto sobe

array([0, 2, 4, 6, 8])

In [8]:
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [9]:
arr = np.zeros((5,5)) # cria uma matriz 5x5
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
ones = np.ones((3,3)) # cria de uns
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# matriz identidade
ind = np.eye(4)
print(ind)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
linspace = np.linspace(0, 10, 3) # espaçamento, quantos números de x até y você quer ver dentro
print(linspace)

[ 0.  5. 10.]


In [13]:
random = np.random.rand(5)
print(random)
print(random * 100)

[0.32943264 0.57906028 0.69567275 0.59245731 0.46035314]
[32.94326437 57.90602787 69.56727489 59.24573107 46.03531376]


In [14]:
multi_dimensional_random = np.random.rand(5, 4, 3)
print(multi_dimensional_random)

[[[0.74606672 0.99905596 0.92322943]
  [0.44310151 0.82623612 0.56071053]
  [0.68142254 0.55252738 0.67903015]
  [0.57390059 0.79123272 0.34106894]]

 [[0.15402529 0.21486366 0.15060537]
  [0.62908053 0.73086566 0.3956513 ]
  [0.64564688 0.97449294 0.10380778]
  [0.12429542 0.23147631 0.71519236]]

 [[0.53970797 0.33521348 0.43712096]
  [0.53662844 0.59937542 0.4987956 ]
  [0.34010315 0.58677894 0.28131761]
  [0.66430477 0.44118167 0.97873996]]

 [[0.86761888 0.04032485 0.42141609]
  [0.23815699 0.75520331 0.46063715]
  [0.25476225 0.68433253 0.43143899]
  [0.00735295 0.41099038 0.2334044 ]]

 [[0.08390583 0.20562698 0.36166049]
  [0.21487052 0.87992311 0.0139329 ]
  [0.33526357 0.12211473 0.04379494]
  [0.92587549 0.13904319 0.04540252]]]


In [15]:
gaussiana = np.random.randn(4)
print(gaussiana)

[ 0.40999501 -0.46451943 -0.67920092  1.51192339]


In [16]:
randit = np.random.randint(0, 100, 10) # randit(do 0, até o 100, 10 números)
print(randit)

[60 22  0  5 94 73 81 31 96 40]


In [18]:
multiplicado = np.random.rand(5) * 100
print(multiplicado)

[10.09387164 54.17796285 82.18686738 43.4175674  23.40905943]


In [21]:
round = np.round(np.random.rand(5)*100, 0) # arredonda para 0 casas decimais
print(round)

[60. 60. 64.  2. 74.]


In [22]:
arr = np.random.rand(25) # vetor de tamnanho 25
print(arr)

[0.94747713 0.80366929 0.14506437 0.57419168 0.45688122 0.10025333
 0.13710524 0.45110995 0.97897594 0.96574162 0.60628775 0.84502071
 0.15704946 0.72677492 0.78597704 0.69184142 0.87462513 0.03466848
 0.52031898 0.43667823 0.27314112 0.88312941 0.53344442 0.97754906
 0.26733991]


In [29]:
# reshape
# arr.reshape(5,5) # deixou de ser vetor de 25 pra ser matriz 5x5, mas o array segue o mesmo, só a visualização que muda
arr = arr.reshape(5,5)
print(arr)


[[0.94747713 0.80366929 0.14506437 0.57419168 0.45688122]
 [0.10025333 0.13710524 0.45110995 0.97897594 0.96574162]
 [0.60628775 0.84502071 0.15704946 0.72677492 0.78597704]
 [0.69184142 0.87462513 0.03466848 0.52031898 0.43667823]
 [0.27314112 0.88312941 0.53344442 0.97754906 0.26733991]]


In [26]:
#shape
arr.shape # parâmetro, não método

(5, 5)

In [31]:
arr.max()

0.9789759383846509

In [32]:
arr.min()

0.034668483725375676

In [33]:
arr.argmax() # posição do maior valor

8

In [ ]:
arr.argmin() # posição do menor valor