# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

OBSERVAÇÃO AO CORRETOR:
Eliminei as caixas de resultado após conferir o resultado.

#### Importe NumPy como np

In [1]:
import numpy as np

#### Crie uma matriz de 10 zeros

In [2]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Crie uma matriz de 10 ones

In [3]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Crie uma matriz de 10 cincos

In [5]:
arr = np.ones(10) * 5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Crie um array de inteiros de 10 até 50

In [6]:
arr = np.arange(10, 51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Crie um array dos numeros pares de 10 até 50

In [8]:
arr = np.arange(10, 51, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Criei uma matriz 3x3 com valores variando de 0 até 8

In [11]:
arr = np.arange(0,9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Crie uma matriz identidade 3x3

In [12]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy para gerar números aleatórios entre 0 e 1

In [33]:
aleatorio = np.random.rand(1)
print(aleatorio)

[0.41028043]


#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [37]:
arr = np.random.randn(25)
print(arr)

[-0.79890384 -0.85160003 -0.83059322 -0.94804152 -0.12738825  1.9959653
  0.25242126 -1.57067612  1.3478933   0.26871911  1.48354907 -1.0703714
  0.93181526  0.11746802 -0.14355163 -1.10511742  0.43364698 -0.66303102
  0.25054997 -0.05763014  0.70731648 -0.06146363  1.64698618  0.87070113
  0.82469381]


#### Crie a seguinte matriz:

In [40]:
arr = np.arange(0.01, 1.01, 0.01)
print(arr)
# ou também np.arange(1, 101) / 100

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [41]:
array_linspace = np.linspace(0, 1, 20)
print(array_linspace)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [42]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [45]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [48]:
mat[3, -1]

20

In [55]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [56]:
mat[-1, 0:]

array([21, 22, 23, 24, 25])

In [61]:
mat[3:, 0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [62]:
soma = np.sum(mat)
print(soma)

325


#### Obter o desvio padrão dos valores em mat

In [63]:
stdev = np.std(mat)
print(stdev)

7.211102550927978


#### Obter a soma de todas as colunas em mat

In [65]:
mat.sum(axis=0) # essa função foi usada por que o eixo(axis) coordenou a soma de cada coluna e colocou em seu índice respectivo
                # se fosse axis = 1, faria a soma das linhas

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])