In [181]:
import numpy as np

In [182]:
arr = np.arange(0, 30, 3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27]


In [183]:
print(arr[3])

9


In [184]:
print(arr[2:5]) # printa os elementos 2 3 e 4

[ 6  9 12]


In [185]:
print(arr[:5]) # printa do elementos 0 ao 4

[ 0  3  6  9 12]


In [186]:
arr[2:] # printa do elemento 3, até o final

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [187]:
arr[2:] = 100 # 2 em diante, tudo é 100
print(arr)

[  0   3 100 100 100 100 100 100 100 100]


Arrays bidimensionais

In [188]:
arr = np.arange(50).reshape((5, 10))
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [189]:
arr.shape # 5 linhas por 10 colunaws

(5, 10)

In [190]:
# slicing
arr[:3][:] # pega as 3 primeiras linhas e todas as colunas
# ^ é o mesmo que arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [191]:
arr2 = arr[:3].copy() # faz uma copia e não aponta
arr2[:] = 100 # isso alterava o arr tbm, pois acha que o arr é uma referencia ao arr1, como se fosse ponteiro. por isso temos que colocar a função .copy()
print(arr2)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [192]:
# indexação de arrays bidimensionais
virugla = arr[1:4,5:] # [linhas,colunas] 1 até a 4 linha, 5 coluna em diante
print(virugla)

[[15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


In [193]:
bol = arr % 2 == 0

In [194]:
print(arr[bol]) # mostra apenas os valores pares

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [195]:
array = np.linspace(0, 100, 30)
print(array)

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


In [196]:
array.shape

(30,)

In [197]:
array = array.reshape(3, 10) # agora é um array bidimensioanl
print(array)

[[  0.           3.44827586   6.89655172  10.34482759  13.79310345
   17.24137931  20.68965517  24.13793103  27.5862069   31.03448276]
 [ 34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
   51.72413793  55.17241379  58.62068966  62.06896552  65.51724138]
 [ 68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
   86.20689655  89.65517241  93.10344828  96.55172414 100.        ]]


In [198]:
array.shape # 3 linhas por 10 colunas

(3, 10)

In [199]:
# quero puxar elementos da coluna de íncidice 2
array[0:2, 2] # só da linha 0 e 1, na coluna 3, pq 0 1 2 

array([13.79310345, 48.27586207, 82.75862069])

In [207]:
# treino -
# puxar elementos da coluna 1 2 3, coluna 5
print(array[0:3, 4])

# puxar o utlimo elemento da ultima coluna ultima linha = 100
print(array[2, 9])

# puxar o primeiro elemento
print(array[0, 0])

[13.79310345 48.27586207 82.75862069]
100.0
0.0
